- hosts: all
  become: yes
  tasks:
    - name: "Install httpd"
      package:
        name: httpd
        state: present

    - name: "Copy index.html"
      copy:
        src: "app/index.html"
        dest: "/var/www/html/index.html"
        owner: root
        group: root
        mode: "0644"

    - name: "Start and enable httpd"
      service:
        name: httpd
        state: started
        enabled: yes
