hosts: all
tasks:
  - name: "Install httpd"
    package:
      name: httpd
      state: present

  - name: "Copy index.html"
    copy:
      src: "app/index.html"
      dest: "/var/www/html/index.html"

  - name: "Start httpd"
    service:
      name: httpd
      state: started
